version: "3.6"

services:
  server:
    build: .
    container_name: lumiere
    image: lumiere
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGO_HOST=mongo # override the mongo host

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodb:/data/db
      - ./mongo/setup.js:/docker-entrypoint-initdb.d/mongo-setup.js:ro
    networks:
      - mongodb
    ports:
      - "27017:27017"
    env_file:
      - ./mongo/.env

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"

volumes:
  mongodb:

networks:
  mongodb:
